language: python
python:
#  - "2.6" -- not supported -- issue:
#     File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/swiftclient/client.py", line 139
#       return {key: safe_value(key, val) for (key, val) in headers}
- "2.7"

#  - "3.3" -- broken on TravisCI -- "The program 'pytest' is currently not installed. To run 'pytest' please ask your administrator to install the package 'python-logilab-common'"
# - "3.4" -- fails: RuntimeError: Python 3.5 or later is required  Couldn't install pip, setuptools, twine or wheel.
- "3.5"
- "3.5-dev"  # 3.5 development branch
- "3.6"
- "3.6-dev"  # 3.6 development branch
- "3.7-dev"  # 3.7 development branch
install:
# Pachyderm package is broken, must be installed from Git:
#- pip install git+https://github.com/pachyderm/python-pachyderm.git
# Update: now it doesn't work for Python 2.x, so exclude it from the tests.
- pip install .
script:
- pytest tests
notifications:
  email: false

# Try to speed up build a little.
cache:
  pip: true
  directories:
  - $HOME/.cache/pip

deploy:
  # Note: only on master branch by default.
  provider: pypi
  skip_existing: true
  user: benblamey
  password:
    secure: KFugflOVA0Pp5TDnK3JuJMEMhlzJCqGK/YKjKtgUBBTBnR6kuWgZxGx3/LbEjaOjcnfrTA6P+gDY7WWZyG5WjZAm0hz8i9LjGz8+kN35gBHKmp7VuBDk2eDlBjOr6IGe8mMFT2NncZ25fEe4rWF1XhRJVI5HZLHhmE7Q0cFPTCpPEgnGs5YIAwci0GtlFsTMupSylip02+OkO3X62A/qkoW/sy7zHOSXmELDkP5Ze3Ul52vfczjFu705odYh6P+qE2X9YIXlHbGIvvJbeEoe2/QK88dJUkQC1Ih7FMOhoNJUg//GzXMLVRRZDJaBge6nM9wK6PMi+rlOkxOI8IZ/SXAK2Aw1rRPcj9cnbkLiQyapYnJhkvx62/nrE4ViENY43a7MszukiCfyswKHVpR1EiOwztLiYsyjs1bL/ncKolBnFWYLexVz5ILlnjgYhVwRPZmhjHeURzcz3fWSfaJGm2YTLCw5dpr/S8gR7TKegsFtTNFw7HP7yVRw1EcMpgiCYRDO3gaN4T305S5XXUQKe/XfjClzRPS+ZFbsmJHCkidVJuByH1rFpajF1QOkRymvJPF5nYOEXHv/9DrTfCeq6TJNPIQ/gfZIbpVgL26ae/bifJm/3OjXeRM5WjIA5WnKuKE57+++bnzGPiVlawnb1kuxomCToMV7IwmGL1nDC7I=